# Generated by Django 4.2.4 on 2023-09-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_locations_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.locations'),
        ),
    ]
