# Generated by Django 4.2.4 on 2023-09-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_locations_parent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='hierarchy_level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
