# Generated by Django 4.2.4 on 2023-09-20 07:31

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_locations_hierarchy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locations',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locations',
            name='parent_location',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning_logs.locations'),
        ),
    ]
