# Generated by Django 4.2.4 on 2023-09-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_locations_level_locations_lft_locations_rght_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
