# Generated by Django 4.2.4 on 2023-09-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_alter_locations_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='tree_id',
        ),
    ]
