# Generated by Django 4.2.4 on 2023-09-20 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_remove_locations_tree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='level',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='rght',
        ),
        migrations.AlterField(
            model_name='locations',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning_logs.locations'),
        ),
    ]
