# Generated by Django 4.2.4 on 2023-09-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_remove_locations_level_remove_locations_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='parent_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_logs.locations'),
        ),
    ]
