# Generated by Django 4.2.4 on 2023-09-20 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0012_alter_locations_parent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='assigned_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locations',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
