# Generated by Django 4.2.4 on 2023-09-20 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_logs', '0014_alter_locations_hierarchy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
