# Generated by Django 4.2.4 on 2023-09-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0015_alter_locations_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='users',
        ),
        migrations.AlterField(
            model_name='locations',
            name='hierarchy_level',
            field=models.PositiveIntegerField(),
        ),
    ]
